### ISSUE TITLE
add support for cargo lock version 4

### ISSUE THREAD

**Issue by ifiokjr** [Ellipsis-Labs/solana-verifiable-build#115]
### Description

When using a recent nightly version, as shown below, the following error is displayed.

#### Error

```bash
# error 
Error: parse error: parse error: invalid Cargo.lock format version: `4`
```

#### Toolchain

```toml
# rust-toolchain.toml
[toolchain]
channel = "nightly-2024-12-19"
```

### Fix

This can be fixed by upgrading the `cargo-lock` dependency to `10.0.0` to support the newest lock file version.
